package com.Server.controller;

import com.Server.dao.PetServiceImpl;
import com.Server.model.Pet;
import org.springframework.web.bind.annotation.*;

import java.util.List;


@RestController
@RequestMapping("/v1")

public class PetApiController {

    //data members

    PetServiceImpl thePetService;

    // Constructor - Generated by IDE
    public PetApiController(PetServiceImpl thePetService) {
        this.thePetService = thePetService;
    }

    @GetMapping ("/pets")
    public List<Pet> anyNameYouWant() {

        return thePetService.getAllPets();
    }

    @PostMapping ("/pets")
    public Pet addPet(@RequestBody Pet newPet ){

        return thePetService.addPet(newPet);
    }

} // end of controller class
